CREATE TABLE [prodcopystg].[Contact]
(
[kore_CheckedOutByName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransactionCurrencyIdName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredSystemUserIdName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_lastcontactedbyidYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_SuiteSalesRepName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EntityImage_URL] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_countryidName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_cityidName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_SSHOriginalSalespersonOKYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_TicketingSalesRepName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_stateorprovinceidName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedOnBehalfByName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedByYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_lastcontractsavedidName] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_TicketingServiceRepYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MasterContactIdYomiName] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_SSHOriginalSalespersonOKName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_GroupSalesRepName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredEquipmentIdName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_GroupSalesRepYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredSystemUserIdYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MasterContactIdName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginatingLeadIdYomiName] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_accountaliasidName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EntityImage_Timestamp] [bigint] NULL,
[ModifiedByName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_TalDoNotDisplayName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_SuiteSalesRepYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_CheckedOutByYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_sourcemarketinglistidName] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_TicketingServiceRepName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_lastcontactedbyidName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModifiedOnBehalfByName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedOnBehalfByYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EntityImage] [varbinary] (max) NULL,
[ModifiedOnBehalfByYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_TicketingSalesRepYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredServiceIdName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefaultPriceLevelIdName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginatingLeadIdName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedByName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModifiedByYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_TalDisplayName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_AddressTypeCode] [int] NULL,
[Address1_City] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Composite] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Country] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_County] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_AddressId] [uniqueidentifier] NULL,
[Address1_Fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_FreightTermsCode] [int] NULL,
[Address1_Latitude] [float] NULL,
[Address1_Line1] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Line2] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Line3] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Longitude] [float] NULL,
[Address1_Name] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_PostalCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_PostOfficeBox] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_PrimaryContactName] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_ShippingMethodCode] [int] NULL,
[Address1_StateOrProvince] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_UPSZone] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_UTCOffset] [int] NULL,
[Address2_AddressTypeCode] [int] NULL,
[Address2_City] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_Composite] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_Country] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_County] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_AddressId] [uniqueidentifier] NULL,
[Address2_Fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_FreightTermsCode] [int] NULL,
[Address2_Latitude] [float] NULL,
[Address2_Line1] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_Line2] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_Line3] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_Longitude] [float] NULL,
[Address2_Name] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_PostalCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_PostOfficeBox] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_PrimaryContactName] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_ShippingMethodCode] [int] NULL,
[Address2_StateOrProvince] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_Telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_Telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_Telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_UPSZone] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_UTCOffset] [int] NULL,
[OwnerId] [uniqueidentifier] NULL,
[OwnerIdName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnerIdYomiName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnerIdDsc] [int] NULL,
[OwnerIdType] [int] NULL,
[OwningUser] [uniqueidentifier] NULL,
[OwningTeam] [uniqueidentifier] NULL,
[AccountId] [uniqueidentifier] NULL,
[AccountIdName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountIdYomiName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ParentContactId] [uniqueidentifier] NULL,
[ParentContactIdName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ParentContactIdYomiName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactId] [uniqueidentifier] NOT NULL,
[DefaultPriceLevelId] [uniqueidentifier] NULL,
[CustomerSizeCode] [int] NULL,
[CustomerTypeCode] [int] NULL,
[PreferredContactMethodCode] [int] NULL,
[LeadSourceCode] [int] NULL,
[OriginatingLeadId] [uniqueidentifier] NULL,
[OwningBusinessUnit] [uniqueidentifier] NULL,
[PaymentTermsCode] [int] NULL,
[ShippingMethodCode] [int] NULL,
[ParticipatesInWorkflow] [bit] NULL,
[IsBackofficeCustomer] [bit] NULL,
[Salutation] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JobTitle] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Department] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NickName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YomiFirstName] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FullName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YomiMiddleName] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YomiLastName] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Anniversary] [datetime] NULL,
[BirthDate] [datetime] NULL,
[GovernmentId] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YomiFullName] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmployeeId] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GenderCode] [int] NULL,
[AnnualIncome] [money] NULL,
[HasChildrenCode] [int] NULL,
[EducationCode] [int] NULL,
[WebSiteUrl] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FamilyStatusCode] [int] NULL,
[FtpSiteUrl] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMailAddress1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpousesName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssistantName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMailAddress2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssistantPhone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMailAddress3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotPhone] [bit] NULL,
[ManagerName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ManagerPhone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotFax] [bit] NULL,
[DoNotEMail] [bit] NULL,
[DoNotPostalMail] [bit] NULL,
[DoNotBulkEMail] [bit] NULL,
[DoNotBulkPostalMail] [bit] NULL,
[AccountRoleCode] [int] NULL,
[TerritoryCode] [int] NULL,
[IsPrivate] [bit] NULL,
[CreditLimit] [money] NULL,
[CreatedOn] [datetime] NULL,
[CreditOnHold] [bit] NULL,
[CreatedBy] [uniqueidentifier] NULL,
[ModifiedOn] [datetime] NULL,
[ModifiedBy] [uniqueidentifier] NULL,
[NumberOfChildren] [int] NULL,
[ChildrensNames] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VersionNumber] [binary] (8) NULL,
[MobilePhone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pager] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Aging30] [money] NULL,
[StateCode] [int] NULL,
[Aging60] [money] NULL,
[StatusCode] [int] NULL,
[Aging90] [money] NULL,
[PreferredSystemUserId] [uniqueidentifier] NULL,
[PreferredServiceId] [uniqueidentifier] NULL,
[MasterId] [uniqueidentifier] NULL,
[PreferredAppointmentDayCode] [int] NULL,
[PreferredAppointmentTimeCode] [int] NULL,
[DoNotSendMM] [bit] NULL,
[ParentCustomerId] [uniqueidentifier] NULL,
[Merged] [bit] NULL,
[ExternalUserIdentifier] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SubscriptionId] [uniqueidentifier] NULL,
[PreferredEquipmentId] [uniqueidentifier] NULL,
[LastUsedInCampaign] [datetime] NULL,
[ParentCustomerIdName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ParentCustomerIdType] [int] NULL,
[TransactionCurrencyId] [uniqueidentifier] NULL,
[OverriddenCreatedOn] [datetime] NULL,
[ExchangeRate] [numeric] (23, 10) NULL,
[ImportSequenceNumber] [int] NULL,
[TimeZoneRuleVersionNumber] [int] NULL,
[UTCConversionTimeZoneCode] [int] NULL,
[AnnualIncome_Base] [money] NULL,
[CreditLimit_Base] [money] NULL,
[Aging60_Base] [money] NULL,
[Aging90_Base] [money] NULL,
[Aging30_Base] [money] NULL,
[ParentCustomerIdYomiName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedOnBehalfBy] [uniqueidentifier] NULL,
[ModifiedOnBehalfBy] [uniqueidentifier] NULL,
[IsAutoCreate] [bit] NULL,
[StageId] [uniqueidentifier] NULL,
[ProcessId] [uniqueidentifier] NULL,
[EntityImageId] [uniqueidentifier] NULL,
[KORE_CompanyName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLIENT_OtherPhone] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_address1_telephone3dncstatus] [bit] NULL,
[kore_stateorprovinceid] [uniqueidentifier] NULL,
[kore_lastcontactedbyid] [uniqueidentifier] NULL,
[new_picklisttest7] [int] NULL,
[KORE_assistantphonedncstatus] [bit] NULL,
[KORE_RegisteredOnline] [bit] NULL,
[Client_EmailAnnouncementContact] [bit] NULL,
[KORE_PatronKey] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client_SuiteSuiteAdministrator] [bit] NULL,
[Client_SuiteContact] [bit] NULL,
[Client_BDActivationRepresentative] [bit] NULL,
[KORE_ListAttributeValue] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_telephone1DNCStatus] [bit] NULL,
[Client_Personal] [bit] NULL,
[KORE_telephone2dnc] [bit] NULL,
[CLIENT_ContactType] [int] NULL,
[KORE_SetParentAccount] [bit] NULL,
[KORE_SeniorityDate] [datetime] NULL,
[KORE_mobilephonedncstatus] [bit] NULL,
[KORE_ListAttributeName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_LastContacted] [datetime] NULL,
[kore_sourcemarketinglistid] [uniqueidentifier] NULL,
[KORE_sponsoraccountnumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_Telephone2DNCChecked] [bit] NULL,
[kore_cityid] [uniqueidentifier] NULL,
[Client_BDDecisionMaker] [bit] NULL,
[KORE_telephone3dnc] [bit] NULL,
[KORE_ScribeStripCompany] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CLIENT_Location] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_countryid] [uniqueidentifier] NULL,
[KORE_AttentionName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client_SuiteConcertTicketContact] [bit] NULL,
[KORE_Telephone1DNC] [bit] NULL,
[KORE_address1_telephone2dncstatus] [bit] NULL,
[KORE_address2_telephone2dncstatus] [bit] NULL,
[KORE_STRId] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_telephone2dncstatus] [bit] NULL,
[Client_ServiceAdministrator] [bit] NULL,
[Client_Children] [int] NULL,
[Client_BDBusinessAssociate] [bit] NULL,
[KORE_PVEPatronKeys] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client_activationrepresentative] [bit] NULL,
[Client_importsuite] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_PVELastUpdate] [datetime] NULL,
[Client_SuiteEmailAnnouncementContact] [bit] NULL,
[KORE_managerphonedncstatus] [bit] NULL,
[Client_SuiteChampionsClub] [bit] NULL,
[KORE_telephone3dncstatus] [bit] NULL,
[Client_flag_christmascard] [bit] NULL,
[Client_suitebusinessaccociate] [bit] NULL,
[KORE_address1_telephone1dncstatus] [bit] NULL,
[Client_SuiteHospitalityConcertClient] [bit] NULL,
[KORE_ImportID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_address2_telephone1dncstatus] [bit] NULL,
[KORE_LastSync] [datetime] NULL,
[KORE_AccountNumber] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client_businessassociate] [int] NULL,
[Client_SuiteDecisionMaker] [bit] NULL,
[KORE_address2_telephone3dncstatus] [bit] NULL,
[Client_BDEmailAnnouncementContact] [bit] NULL,
[Client_StateCanucks] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client_flag_canucksconnection] [bit] NULL,
[KORE_PrimaryAccountNumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_address1milesfromfacility] [numeric] (23, 10) NULL,
[KORE_telephone1dncstatustype] [int] NULL,
[KORE_telephone2dncstatustype] [int] NULL,
[KORE_telephone3dncstatustype] [int] NULL,
[KORE_Type] [int] NULL,
[KORE_IsBillingContact] [bit] NULL,
[KORE_IsPrimaryContact] [bit] NULL,
[kore_accountaliasid] [uniqueidentifier] NULL,
[kore_lastcontractsavedid] [uniqueidentifier] NULL,
[cdi_age] [int] NULL,
[cdi_allowtextmessages] [bit] NULL,
[cdi_facebook] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_gender] [bit] NULL,
[cdi_grade] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_identifiedon] [datetime] NULL,
[cdi_image] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_ip] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_latitude] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_linkedin] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_Longitude] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_partitionkey] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_rowkey] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_score] [int] NULL,
[cdi_social] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_totalscore] [int] NULL,
[cdi_twitter] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_visitorkey] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_archticsids] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_CheckedOutUntil] [datetime] NULL,
[kore_ExternalContactId] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_GroupBuyer] [bit] NULL,
[kore_GroupCategory] [int] NULL,
[kore_HeritageNationality] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_MilesFromFacility] [numeric] (23, 10) NULL,
[kore_MiniPlanHolder] [bit] NULL,
[kore_OverrideCheckoutExpiration] [bit] NULL,
[kore_PrimaryArchticsId] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_SeasonTicketHolder] [bit] NULL,
[kore_SecondaryArchticsName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_SecondaryEmail] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_SuiteBuyer] [bit] NULL,
[kore_TicketingContactType] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_CheckedOutBy] [uniqueidentifier] NULL,
[kore_GroupSalesRep] [uniqueidentifier] NULL,
[kore_SuiteSalesRep] [uniqueidentifier] NULL,
[kore_TicketingSalesRep] [uniqueidentifier] NULL,
[kore_TicketingServiceRep] [uniqueidentifier] NULL,
[client_IsSponsorship] [bit] NULL,
[client_IsTicketing] [bit] NULL,
[client_FlexMerge1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_FlexMerge2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_FlexMerge3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_FlexMerge4] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PaymentPlanNHLSSHCC] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PaymentPlanNHLSSH] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_OnsaleTime] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_OnsaleDate] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PaymentPlanWHLSSH] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_SizeGolfShirt] [int] NULL,
[client_SizeJacket] [int] NULL,
[client_SizeJersey] [int] NULL,
[client_GiftDeliveryMethod] [int] NULL,
[client_MailTrackingNHL] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_MailTrackingWHL] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_Temporary1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_Temporary2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_Temporary3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_TicketingType] [int] NULL,
[koreps_AccountStrippedName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_CompanyId] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_InvalidEmail] [bit] NULL,
[koreps_LastContacted] [datetime] NULL,
[client_RegistryCC] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_SurveyPasswords] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_SurveyURL] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_OilKingsBusTripseats] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_SSHStartDateOilers] [datetime] NULL,
[client_SSHStartDateOilKings] [datetime] NULL,
[client_WHLEnewsBreakingNews] [bit] NULL,
[client_WHLEnewsMedia] [bit] NULL,
[client_WHLEnewsNewsletter] [bit] NULL,
[client_WHLEnewsPostGame] [bit] NULL,
[client_NHLEnewsEvents] [bit] NULL,
[client_NHLEnewsHockeyNews] [bit] NULL,
[client_NHLEnewsMedia] [bit] NULL,
[client_NHLEnewsPostGame] [bit] NULL,
[client_NHLEnewsPreGame] [bit] NULL,
[client_NHLEnewsTicketsContests] [bit] NULL,
[client_NHLEnewsWeeklyNews] [bit] NULL,
[client_SSHEndDateOilers] [datetime] NULL,
[client_SSHEndDateOilKings] [datetime] NULL,
[client_NoEmail] [bit] NULL,
[client_NHLEOCF] [bit] NULL,
[client_SSHRenewalStatusOilKings] [bit] NULL,
[client_LikelihoodtoRenew] [int] NULL,
[client_PrimaryUsage] [int] NULL,
[client_SharePartner] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_ContactType] [int] NULL,
[client_SSHOriginalSalespersonOK] [uniqueidentifier] NULL,
[client_SSHCancReasonOilKings] [int] NULL,
[client_SSHCancOtherTicketsOilKings] [int] NULL,
[client_SSHCancSeatLocationOilKings] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_SSHCancCommentsOilKings] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_SSHCancSourceOilKings] [bit] NULL,
[client_SSHStartSourceOilKings] [int] NULL,
[client_SSHStartCommentsOilKings] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_SSHRenewalFlagOilKings] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_SSHStartSourceOilers] [int] NULL,
[client_SSHStartCommentsOilers] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_SSHCancSourceOilers] [bit] NULL,
[client_SSHCancDocumentOilKings] [int] NULL,
[client_SSHCancDocumentOilers] [int] NULL,
[client_SSHCancReasonOilers] [int] NULL,
[client_SSHCancSeatLocationOilers] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_SSHCancCommentsOilers] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_SSHRenewalFlagOilers] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_EOGEnewsNewsletter] [bit] NULL,
[client_SourceListAudit] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_MKTFirstName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_MKTLastName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_MKTPhoneNumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_MKTCompany] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_MKTCampaign] [int] NULL,
[kore_MKTSkillTesting] [int] NULL,
[kore_JerseyofSeats] [int] NULL,
[kore_JerseyXS] [int] NULL,
[kore_JerseyS] [int] NULL,
[kore_JerseyM] [int] NULL,
[kore_JerseyL] [int] NULL,
[kore_JerseyXL] [int] NULL,
[kore_JerseyXXL] [int] NULL,
[kore_SSHCancPriorStartDateOilers] [datetime] NULL,
[kore_JerseyOrderSubmitted] [int] NULL,
[kore_JerseySource] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_JerseyAudit] [int] NULL,
[client_OKBusTripSubmitted] [int] NULL,
[client_OKBusTripAttendees] [int] NULL,
[client_OKBusTripWaiver] [bit] NULL,
[client_RPContactSourceList] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_RPContactType] [int] NULL,
[client_RPVenueCompany] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_RPRelocationWaveCode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_DoNotStream] [bit] NULL,
[koreps_ficoscore] [int] NULL,
[client_OKSkateAttendees] [int] NULL,
[client_OKSkateSource] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_OKSkateOrderSubmitted] [int] NULL,
[client_OKSkateWaiverAccepted] [bit] NULL,
[client_OilersSSWaiverAccepted] [bit] NULL,
[client_OilersSSAttendees] [int] NULL,
[client_OilersSSSource] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_OilersSSOrderSubmitted] [int] NULL,
[client_OilersSSSkateTime] [int] NULL,
[client_SSHStartYearOilers] [int] NULL,
[client_OKRPOptIn] [bit] NULL,
[client_OKRPOptInSource] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_DisableContactSync] [bit] NULL,
[client_OKPhotoSource] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_OKPhotoofSeats] [int] NULL,
[client_OKPhotoAttendees] [int] NULL,
[client_OKPhotoWaiver] [bit] NULL,
[client_OKPhotoSubmitted] [int] NULL,
[client_RPRegistrySelectionWindowPhase1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_RPRegistryWaveP1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_MediaOEG] [bit] NULL,
[client_RPUpgradeOptIn] [bit] NULL,
[Client_BusinessAccociate] [bit] NULL,
[client_OK5ChalkTalkOptIn] [bit] NULL,
[client_OK5NumberofSeats] [int] NULL,
[client_OK5Attendees] [int] NULL,
[client_OKNewSSHTCAccepted] [bit] NULL,
[client_OKNewSSHTCSubmitted] [int] NULL,
[client_OKNewSSHTCSource] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PRSuiteLocations] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PRSuiteSeats] [int] NULL,
[client_PRSuiteSROs] [int] NULL,
[client_PRSuiteTerm] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PRTheatreBoxLocations] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PRTheatreBoxSeats] [int] NULL,
[client_PRTheatreBoxSROs] [int] NULL,
[client_PRTheatreBoxTerm] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PRChairmansLocationss] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PRChairmansSeats] [int] NULL,
[client_PRChairmansTerm] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PRChairmansPayPlan] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PRLogeTableLocations] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PRLogeTableSeats] [int] NULL,
[client_PRLogeTableTerm] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PRLogeLedgeLocations] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PRLogeLedgeSeats] [int] NULL,
[client_PRLogeLedgeTerm] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PRSuiteContactType] [int] NULL,
[client_PRChairmansContactType] [int] NULL,
[client_PRTheatreBoxContactType] [int] NULL,
[client_PRLogeTableContactType] [int] NULL,
[client_PRLogeLedgeContactType] [int] NULL,
[client_PRArchticsAccount] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_OKViewingPartyAttendees] [int] NULL,
[client_OKViewingPartySubmitted] [int] NULL,
[client_PRNoofClubOZoneSeats] [int] NULL,
[client_PRSuiteLicenseType] [int] NULL,
[client_RogersPlaceEnewsNews] [bit] NULL,
[client_RogersPlaceEnewsEvents] [bit] NULL,
[client_RogersPlaceEnewsFirstName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_RogersPlaceEnewsLastName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_RogersPlaceEnewsPostalCode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_OKInfoSessionSource] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_OKInfoSessionAttendees] [int] NULL,
[client_OKInfoSessionSessionTime] [int] NULL,
[client_PRContractOutstanding] [bit] NULL,
[client_PRContractNotes] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_SyncPriority] [int] NULL,
[koreps_TicketingAccountType] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PRSuspendConcertoffers] [bit] NULL,
[client_PRLELLogeTable] [bit] NULL,
[client_PRLELTbox] [bit] NULL,
[client_PRLELSuites] [bit] NULL,
[client_PRLELOilers] [bit] NULL,
[client_PRLELOilKings] [bit] NULL,
[client_PRLELOtherSports] [bit] NULL,
[client_PRLELGroupHosting] [bit] NULL,
[client_PRLELGeneralInterest] [bit] NULL,
[client_OKContestSignedUp] [bit] NULL,
[client_OKContestSource] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_RegistryRank] [int] NULL,
[client_RogersPlaceEnewsRogersPhoneNumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_RogersPlaceEnewsRogersPreSales] [bit] NULL,
[client_MKTPromoCode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_DeliveryAddressLine1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_DeliveryAddressLine2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_DeliveryFullName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_DeliveryCity] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_DeliveryPostalCode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_DeliveryPhoneNumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_DeliveryProvince] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_MKTReferralSource] [int] NULL,
[client_PRILiveEntertainment] [bit] NULL,
[client_PRIFirstName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PRILastName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PRICompany] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PRIMobilePhone] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PRISkyLounge] [bit] NULL,
[client_PRIGroupSize] [int] NULL,
[client_PRIComments] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_MediaAffiliation] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_MediaPosition] [int] NULL,
[client_OKSalesFirstName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_OKSalesLastName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_OKSalesMobilePhone] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_OKSalesCompany] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_OKSalesSeasonPackages] [bit] NULL,
[client_OKSalesGroupOutings] [bit] NULL,
[client_OKSalesFlexPacks] [bit] NULL,
[client_OKSalesGamePacks] [bit] NULL,
[client_OKPPofSeats] [int] NULL,
[client_OKPPofPasses] [int] NULL,
[client_OilersSSSkaters] [int] NULL,
[client_OKSalesGroupYouthSportsMinorHockey] [bit] NULL,
[client_OKSalesGroupSchoolOutings] [bit] NULL,
[client_prevent_attendees] [int] NULL,
[client_PREventofAttendees] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PRIRentalEmails] [bit] NULL,
[client_PRIPostalCode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_MailTrackingPremium] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PRParkingPasss] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_RPDollars] [int] NULL,
[koreps_ticketingContactType] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PRIInAccountGroup] [bit] NULL,
[client_OilersSSHgeneralmergefield] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PRContractExpireyDate] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PRInsCertificateExpiryDate] [datetime] NULL,
[client_PRInsHostLiquorLiability] [bit] NULL,
[client_PRInsGeneralLiability] [bit] NULL,
[client_PRInsCertificateUploaded] [bit] NULL,
[client_PRInsAdditionalInsured] [bit] NULL,
[client_PRInsComments] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PRInsCertificateHolder] [bit] NULL,
[client_PRInsDeductible] [bit] NULL,
[client_PRInsPolicy] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PRInsInsuringCompany] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PRInsInsured] [bit] NULL,
[client_OKGiftingSSMType] [int] NULL,
[client_OKGiftingofSeats] [int] NULL,
[client_OKGiftingPennant] [int] NULL,
[client_OKGiftingFoundersPhoto] [int] NULL,
[client_OKGiftingClubPhoto] [int] NULL,
[client_OKGiftingCardSet] [int] NULL,
[client_OKGiftingFanZoneSign] [int] NULL,
[client_OKGiftingFramedPhoto] [int] NULL,
[client_OKGiftingBobblehead] [int] NULL,
[client_OK5ChalkTalkSubmitted] [int] NULL,
[client_OKWave] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_OKSelectionWindow] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_OKVIPWave] [int] NULL,
[client_OKServiceSelectionWindow] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_OKServiceSelectionWave] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_OKSalesBirthday] [bit] NULL,
[client_OKGiftingClock] [int] NULL,
[client_OilersPlayoffPriorityDrawPremium] [bit] NULL,
[client_OilersPlayoffPriorityDrawBowl] [bit] NULL,
[client_OilersPlayoffPriorityDrawPowerPack] [bit] NULL,
[client_MKTPostalCode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_OilersSNSKYOpenHouseRSVP] [bit] NULL,
[client_OilersSNSKYOpenHouseAttendees] [int] NULL,
[client_LMTAFirstName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_LMTALastName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_LMTAMobilePhoneNumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_LMTAPostalCode] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_LMTAOptIn] [bit] NULL,
[client_LMTAPassword] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[cdi_TalDoNotDisplay] [uniqueidentifier] NULL,
[cdi_TalDisplay] [uniqueidentifier] NULL,
[client_OilersPlayoffPriorityDrawBowlSSHMerge] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_OilersPlayoffPriorityDrawPowerPackMerge] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_OilersPlayoffPriorityDrawPremiumMerge] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_OilersPlayoffPriorityDrawStaffMerge] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_MKTAttendees] [int] NULL,
[client_MKTWaiverorTerms] [bit] NULL,
[client_MKTWinner] [bit] NULL,
[client_OKJerseyMensS] [int] NULL,
[client_OKJerseyMensM] [int] NULL,
[client_OKJerseyMensL] [int] NULL,
[client_OKJerseyMensXL] [int] NULL,
[client_OKJerseyMensXXL] [int] NULL,
[client_OKJerseyMensXXXL] [int] NULL,
[client_OKJerseyWomenS] [int] NULL,
[client_OKJerseyWomensM] [int] NULL,
[client_OKJerseyWomensL] [int] NULL,
[client_OKJerseyWomensXL] [int] NULL,
[client_OKJerseyYouthSM] [int] NULL,
[client_OKJerseyYouthLXL] [int] NULL,
[client_OKJerseyofSeats] [int] NULL,
[client_OKJerseyAudit] [int] NULL,
[client_OKJerseySource] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_OKJerseySubmitted] [bit] NULL,
[client_SourceListID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_MKTTransferFirstName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_MKTTransferLastName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_MKTTransferEmail] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_RPRelocationSelectionWindow] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_SSHCancPriorStartDateOK] [datetime] NULL,
[client_OilersSSHStory] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PRPaymentPlan] [int] NULL,
[client_PRHospitalityTracker] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_OKInfoSessionAdditionalGuests] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_LMTAReferralSource] [int] NULL,
[client_NHLEnewsReferralSource] [int] NULL,
[client_PRIReferralSource] [int] NULL,
[client_DeliveryCurrentAddressConfirmation] [bit] NULL,
[client_RegistryRefundCheckIssued] [bit] NULL,
[client_RegistryPhotoConsent] [bit] NULL,
[client_RegistryDateTimeAvailability] [bit] NULL,
[client_RegistryAgeRange] [int] NULL,
[client_PSSMigration] [int] NULL,
[client_MKTCompanySize] [int] NULL,
[client_MKTIndustry] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_OKGiftingCardSet2] [int] NULL,
[client_MKTSessionTime] [int] NULL,
[CopyLoadDate] [datetime] NOT NULL CONSTRAINT [DF__Contact__CopyLoa__6FE99F9F] DEFAULT (getdate())
)
GO
ALTER TABLE [prodcopystg].[Contact] ADD CONSTRAINT [PK__Contact__5C66259B2B6D23DB] PRIMARY KEY CLUSTERED  ([ContactId])
GO
