CREATE TABLE [prodcopystg].[Account]
(
[kore_secondarysalespersonidYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_externalreportingpartneridName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_PremiumSalespersonIdName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_SecondaryContactYomiName] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredEquipmentIdName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_authorizedsignoridYomiName] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrimaryContactIdName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModifiedOnBehalfByYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_accountexecutiveidName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_coordinatoridName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_SecondarySuiteContaactYomiName] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_NBACategoryIdName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_authorizedsignoridName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredSystemUserIdYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MasterAccountIdYomiName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_BillingContactName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedByYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_AgencyIdName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_industryidName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_CoordinatorSecondaryName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrimaryContactIdYomiName] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TerritoryIdName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_externalrevenuecontactName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_salespersonidYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_sourcemarketinglistidName] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModifiedOnBehalfByName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_AgencyIdYomiName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MasterAccountIdName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModifiedByName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_CurrentAgencyName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_accountexecutiveidYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_SalespersonSecondaryYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_SecondarySuiteContaactName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_billingcityidName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EntityImage_Timestamp] [bigint] NULL,
[koreps_PremiumSalespersonIdYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ParentAccountIdName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedOnBehalfByName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TransactionCurrencyIdName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_SecondaryContactName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_CurrentAgency2YomiName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EntityImage_URL] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_CheckedOutByYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_SalespersonSecondaryName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_billingcontactidYomiName] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EntityImage] [varbinary] (max) NULL,
[kore_NBASponsorIdName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_CurrentAgency2Name] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_stateorprovinceidName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_salespersonidName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_secondarycoordinatoridName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_secondarysalespersonidName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_NHLIndustryIdName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_externalrevenuecontactYomiName] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PrimarySuiteContactYomiName] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ParentAccountIdYomiName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_CurrentAgencyYomiName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_PremiumCoordinatorIdYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_lastcontractsavedidName] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_cityidName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_CheckedOutByName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedByName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedOnBehalfByYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModifiedByYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredSystemUserIdName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_SalesSeasonName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_LastContactedByIdName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_CoordinatorSecondaryYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_billingcontactidName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_secondarycoordinatoridYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PreferredServiceIdName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginatingLeadIdYomiName] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_billingcountryidName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OriginatingLeadIdName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_LastContactedByIdYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_PremiumCoordinatorIdName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_countryidName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_RelName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_coordinatoridYomiName] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefaultPriceLevelIdName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_BillingContactYomiName] [nvarchar] (450) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_accountgroupidName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_billingstateprovinceidName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PrimarySuiteContactName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_StateofIncorporationIdName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_AddressTypeCode] [int] NULL,
[Address1_City] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Composite] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Country] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_County] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_AddressId] [uniqueidentifier] NULL,
[Address1_Fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_FreightTermsCode] [int] NULL,
[Address1_Latitude] [float] NULL,
[Address1_Line1] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Line2] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Line3] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Longitude] [float] NULL,
[Address1_Name] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_PostalCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_PostOfficeBox] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_PrimaryContactName] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_ShippingMethodCode] [int] NULL,
[Address1_StateOrProvince] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_Telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_UPSZone] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1_UTCOffset] [int] NULL,
[Address2_AddressTypeCode] [int] NULL,
[Address2_City] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_Composite] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_Country] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_County] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_AddressId] [uniqueidentifier] NULL,
[Address2_Fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_FreightTermsCode] [int] NULL,
[Address2_Latitude] [float] NULL,
[Address2_Line1] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_Line2] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_Line3] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_Longitude] [float] NULL,
[Address2_Name] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_PostalCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_PostOfficeBox] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_PrimaryContactName] [nvarchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_ShippingMethodCode] [int] NULL,
[Address2_StateOrProvince] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_Telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_Telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_Telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_UPSZone] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2_UTCOffset] [int] NULL,
[OwnerId] [uniqueidentifier] NULL,
[OwnerIdName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnerIdYomiName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnerIdDsc] [int] NULL,
[OwnerIdType] [int] NULL,
[OwningUser] [uniqueidentifier] NULL,
[OwningTeam] [uniqueidentifier] NULL,
[AccountId] [uniqueidentifier] NULL,
[AccountCategoryCode] [int] NULL,
[TerritoryId] [uniqueidentifier] NULL,
[DefaultPriceLevelId] [uniqueidentifier] NULL,
[CustomerSizeCode] [int] NULL,
[PreferredContactMethodCode] [int] NULL,
[CustomerTypeCode] [int] NULL,
[AccountRatingCode] [int] NULL,
[IndustryCode] [int] NULL,
[TerritoryCode] [int] NULL,
[AccountClassificationCode] [int] NULL,
[BusinessTypeCode] [int] NULL,
[OwningBusinessUnit] [uniqueidentifier] NULL,
[OriginatingLeadId] [uniqueidentifier] NULL,
[PaymentTermsCode] [int] NULL,
[ShippingMethodCode] [int] NULL,
[PrimaryContactId] [uniqueidentifier] NULL,
[ParticipatesInWorkflow] [bit] NULL,
[Name] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountNumber] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Revenue] [money] NULL,
[NumberOfEmployees] [int] NULL,
[Description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SIC] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnershipCode] [int] NULL,
[MarketCap] [money] NULL,
[SharesOutstanding] [int] NULL,
[TickerSymbol] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StockExchange] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WebSiteURL] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FtpSiteURL] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMailAddress1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMailAddress2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMailAddress3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotPhone] [bit] NULL,
[DoNotFax] [bit] NULL,
[Telephone1] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotEMail] [bit] NULL,
[Telephone2] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Telephone3] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DoNotPostalMail] [bit] NULL,
[DoNotBulkEMail] [bit] NULL,
[DoNotBulkPostalMail] [bit] NULL,
[CreditLimit] [money] NULL,
[CreditOnHold] [bit] NULL,
[IsPrivate] [bit] NULL,
[CreatedOn] [datetime] NULL,
[CreatedBy] [uniqueidentifier] NULL,
[ModifiedOn] [datetime] NULL,
[ModifiedBy] [uniqueidentifier] NULL,
[VersionNumber] [binary] (8) NULL,
[ParentAccountId] [uniqueidentifier] NULL,
[Aging30] [money] NULL,
[StateCode] [int] NULL,
[Aging60] [money] NULL,
[StatusCode] [int] NULL,
[Aging90] [money] NULL,
[PreferredAppointmentDayCode] [int] NULL,
[PreferredSystemUserId] [uniqueidentifier] NULL,
[PreferredAppointmentTimeCode] [int] NULL,
[Merged] [bit] NULL,
[DoNotSendMM] [bit] NULL,
[MasterId] [uniqueidentifier] NULL,
[LastUsedInCampaign] [datetime] NULL,
[PreferredServiceId] [uniqueidentifier] NULL,
[PreferredEquipmentId] [uniqueidentifier] NULL,
[ExchangeRate] [numeric] (23, 10) NULL,
[UTCConversionTimeZoneCode] [int] NULL,
[OverriddenCreatedOn] [datetime] NULL,
[TimeZoneRuleVersionNumber] [int] NULL,
[ImportSequenceNumber] [int] NULL,
[TransactionCurrencyId] [uniqueidentifier] NULL,
[CreditLimit_Base] [money] NULL,
[Aging30_Base] [money] NULL,
[Revenue_Base] [money] NULL,
[Aging90_Base] [money] NULL,
[MarketCap_Base] [money] NULL,
[Aging60_Base] [money] NULL,
[YomiName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedOnBehalfBy] [uniqueidentifier] NULL,
[ModifiedOnBehalfBy] [uniqueidentifier] NULL,
[StageId] [uniqueidentifier] NULL,
[ProcessId] [uniqueidentifier] NULL,
[EntityImageId] [uniqueidentifier] NULL,
[Client_ProspectSeason] [int] NULL,
[Client_ProspectStatus] [int] NULL,
[Client_ProspectObjectives] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client_ProspectDescription] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client_ProspectDate] [datetime] NULL,
[KORE_lastcontactedactivityid] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client_BillingStreet3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_Contact] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client_BillingMainPhone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_billingcountryid] [uniqueidentifier] NULL,
[KORE_address2_telephone1dncstatus] [bit] NULL,
[Client_CanucksCategory] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client_CountryCanucks] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_address1_telephone2dncstatus] [bit] NULL,
[client_accountgroupid] [uniqueidentifier] NULL,
[kore_cityid] [uniqueidentifier] NULL,
[Client_dsa] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client_NextExpectedCollectionDate] [datetime] NULL,
[KORE_address1_telephone1dncstatus] [bit] NULL,
[KORE_telephone3dncstatus] [bit] NULL,
[kore_coordinatorid] [uniqueidentifier] NULL,
[KORE_telephone1dncstatus] [bit] NULL,
[Client_importindustry] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_VendorAccountNumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_LastSync] [datetime] NULL,
[kore_countryid] [uniqueidentifier] NULL,
[Client_CityCanucks] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_billingstateprovinceid] [uniqueidentifier] NULL,
[kore_industryid] [uniqueidentifier] NULL,
[kore_authorizedsignorid] [uniqueidentifier] NULL,
[KORE_Agency] [int] NULL,
[KORE_SponsorAccountNumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_address2_telephone3dncstatus] [bit] NULL,
[Client_ParkingStall1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_accountexecutiveid] [uniqueidentifier] NULL,
[KORE_nextcontactactivityid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_Type] [int] NULL,
[Client_importprimaryrep] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client_StateCanucks] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_sourcemarketinglistid] [uniqueidentifier] NULL,
[Client_importcategory] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_address1_telephone3dncstatus] [bit] NULL,
[Client_sponsoraccountnumber2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_NextContact] [datetime] NULL,
[KORE_AuthorizedSignor] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_StateofIncorporation] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client_importsecrep] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_telephone2dncstatus] [bit] NULL,
[Client_LastContacted] [datetime] NULL,
[KORE_CallLeters] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client_BillingStreet1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client_BillingFax] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client_ClassID] [int] NULL,
[Client_CollectionComments] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_billingcityid] [uniqueidentifier] NULL,
[KORE_address2_telephone2dncstatus] [bit] NULL,
[Client_BillingPostalCode] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_billingcontactid] [uniqueidentifier] NULL,
[CLIENT_RelationshipStartDate] [datetime] NULL,
[kore_salespersonid] [uniqueidentifier] NULL,
[KORE_LastContacted] [datetime] NULL,
[KORE_LegalName] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_stateorprovinceid] [uniqueidentifier] NULL,
[CLIENT_Tier] [int] NULL,
[Client_BillingAddressSameasPrimaryAddress] [bit] NULL,
[KORE_ARNotes] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_Band] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client_ParkingStall2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client_BillingStreet2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Client_CategoryCompetition] [bit] NULL,
[Client_importsuite] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_STRID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_StrippedName] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[KORE_AgencyId] [uniqueidentifier] NULL,
[kore_NBACategoryId] [uniqueidentifier] NULL,
[kore_NBASponsorId] [uniqueidentifier] NULL,
[KORE_StateofIncorporationId] [uniqueidentifier] NULL,
[client_TaxExemptStatus] [bit] NULL,
[KORE_createdbyaccountalias] [bit] NULL,
[KORE_test] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PrimarySuiteContact] [uniqueidentifier] NULL,
[client_SecondaryContact] [uniqueidentifier] NULL,
[client_SecondarySuiteContaact] [uniqueidentifier] NULL,
[client_Rel] [uniqueidentifier] NULL,
[kore_lastcontractsavedid] [uniqueidentifier] NULL,
[kore_secondarysalespersonid] [uniqueidentifier] NULL,
[kore_secondarycoordinatorid] [uniqueidentifier] NULL,
[kore_TaxExemptStatus] [bit] NULL,
[kore_Headquarters] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_USOffice] [nvarchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_externalreportingpartnerid] [uniqueidentifier] NULL,
[client_NHLIndustryId] [uniqueidentifier] NULL,
[cdi_allowtextmessages] [bit] NULL,
[kore_ExternalAccountID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_issponsorship] [bit] NULL,
[client_isticketing] [bit] NULL,
[koreps_StrippedName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_PremiumSalespersonId] [uniqueidentifier] NULL,
[koreps_PremiumCoordinatorId] [uniqueidentifier] NULL,
[koreps_FutureLTV] [money] NULL,
[koreps_futureltv_Base] [money] NULL,
[koreps_LTVToDate] [money] NULL,
[koreps_ltvtodate_Base] [money] NULL,
[koreps_TotalLifetimeValue] [money] NULL,
[koreps_totallifetimevalue_Base] [money] NULL,
[client_SICCodeDescription] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_SourceList] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_SourceListID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_SourceListAudit] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[kore_externalrevenuecontact] [uniqueidentifier] NULL,
[koreps_CheckedOutUntil] [datetime] NULL,
[koreps_DoNotStream] [bit] NULL,
[koreps_FinanceAccountNumber] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_FinanceIsSynced] [bit] NULL,
[koreps_financemodifieddate] [datetime] NULL,
[koreps_HasCheckedOutContact] [bit] NULL,
[koreps_LastContacted] [datetime] NULL,
[koreps_numberofcontacts] [int] NULL,
[koreps_CheckedOutBy] [uniqueidentifier] NULL,
[koreps_CurrentlyBeingWorked] [bit] NULL,
[koreps_MilesFromFacility] [numeric] (23, 10) NULL,
[koreps_LastContactedById] [uniqueidentifier] NULL,
[koreps_SyncPriority] [int] NULL,
[koreps_LegalName] [nvarchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_CurrentAgency] [uniqueidentifier] NULL,
[client_AgencyNotes] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_CurrentAgency2] [uniqueidentifier] NULL,
[dnb_dnbinitialassociationdate] [datetime] NULL,
[dnb_dnbinitialassociationstatus] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[koreps_CoordinatorSecondary] [uniqueidentifier] NULL,
[koreps_SalespersonSecondary] [uniqueidentifier] NULL,
[client_BillingContact] [uniqueidentifier] NULL,
[client_Sponsor] [money] NULL,
[client_sponsor_Base] [money] NULL,
[client_Hospitality] [money] NULL,
[client_hospitality_Base] [money] NULL,
[client_SalesSeason] [uniqueidentifier] NULL,
[client_ToClose] [int] NULL,
[client_Status] [int] NULL,
[client_DealSheetType] [int] NULL,
[client_Asset1] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_Asset2] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_Asset3] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_Asset4] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_Asset5] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_Asset6] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_AdditionalAssets] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_WHLSponsor] [money] NULL,
[client_whlsponsor_Base] [money] NULL,
[client_PGA] [money] NULL,
[client_pga_Base] [money] NULL,
[client_PBR] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_EOCFSponsor] [money] NULL,
[client_eocfsponsor_Base] [money] NULL,
[client_ContractTerm] [numeric] (23, 10) NULL,
[client_Asset7] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_Asset8] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_Asset9] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_Asset10] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_Asset11] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[client_PBRSponsor] [money] NULL,
[client_pbrsponsor_Base] [money] NULL,
[CopyLoadDate] [datetime] NOT NULL CONSTRAINT [DF_ProdCopy_Account] DEFAULT (getdate())
)
GO
